### ISSUE TITLE
New Appointment Back End

### ISSUE THREAD

**Issue by mpross512** [UTDallasEPICS/Local-Good-Inventory#12]
Need to update the back end to properly support the adjusted appointment UI front end with the follwing additions:
- Add appointment time for user to the database, not just the date
- Store/retrieve values in database for the 
  - Maximum Number of people per time slot
  - Valid days of the week for appointments
  - Valid times/time slots
- Create a document in the database to store these values (See recommendation in #14)

**Comment by Aarian-A** [comment]
Days: F & Sat
Open/Close: 9:30 - 11:30
Timeslots: 15 minutes each
