### ISSUE TITLE
Admin Page Appointment UI

### ISSUE THREAD

**Issue by mpross512** [UTDallasEPICS/Local-Good-Inventory#13]
Create an **Appointment**  section on the admin page with appropriate elements so a user on the admin page can
- Change which days they allow people to visit the market
- Change which times on a per-day basis people can visit the market
- Change the size of the time slots, from 5 minute segments from 5-60
- Change the amount of appointments allowed for each time slot

**Comment by Aarian-A** [comment]
Days: F & Sat
Open/Close: 9:30 - 11:30
Timeslots: 15 minutes each
