### ISSUE TITLE
Admin Page Appointment Back End

### ISSUE THREAD

**Issue by mpross512** [UTDallasEPICS/Local-Good-Inventory#14]
Need to link the UI front end of the admin page appointment section (#13) to update settings in database for
- Days available for appointments
- Times of each day available for appointments
- Number of appointments allowed per each time slot
- Length of each time slot

I recommend you start by creating a model in the `src/app/models` folder with the necessary variables

**Comment by Aarian-A** [comment]
Days: F & Sat
Open/Close: 9:30 - 11:30 
Timeslots: 15 minutes each
