### ISSUE TITLE
Add Language Option to Navbar

### ISSUE THREAD

**Issue by mpross512** [UTDallasEPICS/Local-Good-Inventory#19]
Instead of having a home page with different language options, the language options should instead be located in a dropdown on the top right of the navbar

Look at this site https://bulma.io/documentation/components/navbar/ for info on adding a dropdown to our navbar. Our navbar component is located in the `src/app/components` folder

**Comment by Aarian-A** [comment]
Added the drop down, all that's left is to route the languages and figure out a way to translate them.
